### PR TITLE
Support for node@4 and npm@2

### PR DESCRIPTION
**Pull request by alexindigo**
- Made tests to pass in node@4.
- Added coverage
- Fixed missing dependencies
- Added pre-commit hook

/cc @dntrkv

### CODE REVIEW

**Comment by gajus** [comment]
> Made tests to pass in node@4.
> Fixed missing dependencies

`react-css-modules` is working in Node v4. It is only the tests that do not pass. The reason tests do not pass is because NPM v2 does not flatten its dependency tree. Adding dependencies of another project to this project to make it work is not an optimal solution because there is no way to inspect dead dependencies.

> Added coverage

I only see "coveralls" dependency added.

> Added pre-commit hook

You cannot commit a Git hook to a repository.

Besides, making changes such as renaming ./tests to ./test is incredibly biased.

If you'd like to add test coverage, please raise a separate PR.

**Comment by alexindigo** [comment]
> react-css-modules is working in Node v4. It is only the tests that do not pass.

I'm confused, how do you know that it works in v4 if tests don't pass? :)

> Adding dependencies of another project to this project...

This project has babel plugins in it's dependencies in babelrc file, so including them as devDependencies seems only logical.

>  because there is no way to inspect dead dependencies.

Do you mind to elaborate on "inspecting dead dependencies"? Thank you.

> I only see "coveralls" dependency added.

And nyc + istanbul and updated `test` script to run tests with coverage (and yes report it to coveralls).

> You cannot commit a Git hook to a repository.

I can't. But there is `pre-commit` module, that installs pre-commit hook when dev dependencies installed.

> Besides, making changes such as renaming ./tests to ./test is incredibly biased.

`test` folder ignored by istanbul by default, but if you have strong feeling towards `tests`, I can add istanbul config and make ignore `tests`. It's your call.

**Comment by gajus** [comment]
> I'm confused, how do you know that it works in v4 if tests don't pass? :)

Because tests pass. Linting doesn't.

**Comment by gajus** [comment]
The primary problem with this PR is that it is a mixed bag of changes.

**Comment by gajus** [comment]
> This project has babel plugins in it's dependencies in babelrc file, so including them as devDependencies seems only logical.

I am referring to:

```
 +    "eslint-plugin-babel": "^3.3.0",
 +    "eslint-plugin-flowtype": "^2.4.0",
 +    "eslint-plugin-import": "^1.12.0",
 +    "eslint-plugin-jsdoc": "^2.3.1",
 +    "eslint-plugin-lodash": "^1.10.1",
 +    "eslint-plugin-mocha": "^4.3.0",
 +    "eslint-plugin-no-use-extend-native": "^0.3.7",
 +    "eslint-plugin-promise": "^2.0.0",
 +    "eslint-plugin-react": "^6.0.0",
 +    "eslint-plugin-sorting": "^0.3.0",
```

**Comment by gajus** [comment]
> Do you mind to elaborate on "inspecting dead dependencies"? Thank you.

Finding unused dependencies.

**Comment by gajus** [comment]
> I can't. But there is pre-commit module, that installs pre-commit hook when dev dependencies installed.

I am not a fan of pro-commit hooks. Because they slow down the workflow.

There is no need for a pre-commit hook, because if there is something wrong, it will be rejected at the time when the PR does not pass the CI.

**Comment by alexindigo** [comment]
Good morning :)

> The primary problem with this PR is that it is a mixed bag of changes.

I see it as one step towards better contributors experience. Originally I came here to create very different kind of PR, but when I ran tests (before I touched any file) they failed, so one thing led to another. :) I see making tests pass on major platform, adding pre-commit hook and coverage as all related to better state of the project.

> Finding unused dependencies.

Ok, I see your point. How about I'll make linting conditional for travis, so it'd run only for npm@3 setups?

> I am not a fan of pre-commit hooks. Because they slow down the workflow.

Funny, I see it as exactly opposite – in my book they speed up the workflow by eliminating need for extra round trip to github/PR/travis and will notify developer that something went south right on spot.

But again, if you don't like this idea, I can totally undo this change.

And now to address elephant in the room, the thing that started this PR on the first place:

> Because tests pass. Linting doesn't.

Tests fail, because these packages were missing:

```
+    "babel-plugin-transform-class-properties": "^6.11.5",
+    "babel-plugin-transform-es2015-classes": "^6.9.0",
```

Gist of the full experience:
https://gist.github.com/alexindigo/30258a479c85a04dc1e7d0dddce0aadb

So, how about. I'll make linting conditional, take it out from pre-commit hook or if you really want it, will undo pre-commit hook altogether. Would it work for you?

Please let me know if there are adjustments you'd like to see here.
Thank you.

**Comment by gajus** [comment]
@alexindigo 

> Ok, I see your point. How about I'll make linting conditional for travis, so it'd run only for npm@3 setups?

That sounds like an option. In fact, I have remembered your PR when working on a similar issue.

https://github.com/gajus/gitinfo/blob/d974e01b8d984f2ef2f99766b502b07a2a267dd0/.travis.yml#L8

Since NPM is the culprit of the issue, I am enabling Node v4 tests by simply installing NPM v3.

> Funny, I see it as exactly opposite – in my book they speed up the workflow by eliminating need for extra round trip to github/PR/travis and will notify developer that something went south right on spot.

I came to this subject while writing a blog post about the perfect CI flow. You are right – my conclusion was that pre-commit linting hook does increase productivity, but only if linting is applied to the staged lines in the code.

For this task, there is https://github.com/okonet/lint-staged, though it appears to be a fragile state. I haven't had a chance to test it yet.

**Comment by gajus** [comment]
0cf0c2cede212bb087270e5b55268e06b87555bc

**Pull request closed without merging**
