### PR TITLE
Add babel-plugin-transform-object-assign to transform Object.assign

### PR DESCRIPTION
**Pull request by nguquen**
Add babel-plugin-transform-object-assign to transform Object.assign in extendReactClass.js

### CODE REVIEW

**Comment by gajus** [comment]
Whats the reason?

**Comment by nguquen** [comment]
If not, it will throw `Object doesn't support property or method "assign"` on IE 11, and we got blank page on IE 11 or old browsers.

**Comment by gajus** [comment]
Polyfill-ing is not responsibility of `react-css-modules`.

Use https://polyfill.io/

**Comment by mirovelk** [comment]
Transforming Object.assign is not the same as polyfilling. There are situations when polyfill in browser can't be used (is not allowed).

By having Object.assign in your code you are also disabling testing in phantomjs as well (where Object.assign is not supported as well).

Most libraries use https://www.npmjs.com/package/object-assign or https://www.npmjs.com/package/babel-plugin-transform-object-assign to prevent these issues.

**Comment by progman32** [comment]
One of the advantages of css-modules is isolation. Given this, it seems odd to require the mutation of the host environment (polyfilling) in order to use css-modules, especially in library scenarios.

**Pull request closed without merging**
