### PR TITLE
Removed unnecessary file and dependency.

### PR DESCRIPTION
**Pull request by Semigradsky**

### CODE REVIEW

**Comment by gajus** [comment]
lodash use was planned for config management. It is now implemented. https://github.com/gajus/react-css-modules/commit/60c1f69d5b61834ab1b108fb4b6bd3363b91ba54

Thank you for the pull request, though. :+1:

**Comment by Semigradsky** [comment]
You do not think about using native methods? Lodash is a very large dependence.

For example:
```js
unknownProperties = _.difference(_.keys(userConfig), knownProperties);
```
may be changed to
```js
unknownProperties = Object.keys(userConfig).filter(x => knownProperties.indexOf(x) === -1);
```

and
```js
_.forEach(userConfig, (value, name) => {
```
to
```js
Object.keys(userConfig).forEach(name => {
```

**Comment by gajus** [comment]
@Semigradsky I am not importing the entire lodash package. Only the individual functions, see https://github.com/gajus/react-css-modules/blob/master/src/utils.js#L1-L3. The overhead is negligible.

**Comment by Semigradsky** [comment]
I understood you. There are also separate modules (https://www.npmjs.com/browse/keyword/lodash-modularized), but I'm not sure that they are better.

**Pull request closed without merging**
