### PR TITLE
add more stable and backward-compatible stateless function detection

### PR DESCRIPTION
**Pull request by lukewestby**
checking that the `Component` passed in has a `prototype` and that prototype has a `render` method

addresses #40

### CODE REVIEW

**Comment by lukewestby** [comment]
it looks like travis-ci is having trouble reaching npm

**Comment by gajus** [comment]
https://github.com/gajus/react-css-modules/commit/ed3b28c25d2a0b07dde5fe9de69d1ea4691909de

**Comment by gajus** [comment]
Thank you

**Comment by lukewestby** [comment]
awesome, thank you!

**Pull request closed without merging**
