### PR TITLE
webpack config examples in README were outdated.

### PR DESCRIPTION
**Pull request by ipatch**
I hope this helps save some people some time, when trying to set this up with the latest `webpack-dev-server`

cheers 🍺
Chris

### CODE REVIEW

**Comment by gajus** [comment]
Please revert the style changes and restrict the PR to the content changes.

**Comment by ipatch** [comment]
doh 🍩 looks like [prettier](https://github.com/prettier/prettier) got the best of this commit.

**Comment by mwanago** [comment]
This one really took me quite a lot of time. It is a shame that it is not merged.

**Comment by gajus** [comment]
Prettier.

**Pull request closed without merging**
