### PR TITLE
allow array for styleName

### PR DESCRIPTION
**Pull request by FredyC**
Yeah, I've read about using composition over multiple style names, but I just don't see how to apply that easily in my case. I have an element that can have like 4 different states, some can be even combined. With composition I would need to create combination for every case and that would make my conditions kinda a messy.

```css
.bullet {
    width: 15px;
    height: 18px;
}
.bulletZoom {
    cursor: pointer;
}
.bulletZoom:hover {
    background-color: #aaa;
}
.bulletChildren {
    background-color: #ddd;
}
.bulletSelected {
    color: red;
}
.bulletError {
    color: #aaa;
}
```

If you have a suggestion how to handles this using composition, I would to hear that. Otherwise I could really use this pull request so I don't need to concatenate style names just to be split later.

### CODE REVIEW

**Comment by gajus** [comment]
> I have an element that can have like 4 different states, some can be even combined.

can you list what these states are and how they can be combined?

There is no scenario where using multiple style names will produce a more readable code than using composition. The more likely scenario is that you are misidentifying the states/ separation of states. I will happily help if you produce a specific example describing the role of the element, different states it can have and how the states are mixed.

There is no planned support for array input unless React `className` adds array support too.

**Comment by gajus** [comment]
> some can be even combined.

States by definition cannot be combined. State is, well ... state. "multiple states" would constitute a new state. A composition pattern is only guiding you the right way.

**Comment by FredyC** [comment]
Well you may see my states in the CSS above. All these combinations are perfectly valid "states" for the _bullet_ in my application. I am really not sure how I could simplify this when I need different colors for a different states. Should I get rid of CSS and put colors into the code?

[bullet, bulletZoom]
[bullet, bulletError]
[bullet, bulletZoom, bulletError]
[bullet, bulletZoom, bulletSelected]
[bullet, bulletError, bulletChildren]
[bullet, bulletChildren, bulletSelected]

Using composition I would need to create styles like

bullet-zoom
bullet-error
bullet-zoom-error
bullet-zoom-selected
bullet-error-children
bullet-children-error

Currently in the code I can do something this

```js
const names = ['bullet'];
if (this.canZoom()) {
    names.push('bulletZoom');
}
if (this.hasError()) {
    names.push('bulletError');
}
```

With the composition I would need to test every possible combination to actually figure out name of composed style. Something like ...

```js
let name = 'bullet';
if (this.canZoom()) {
    name = 'bullet-zoom';
}
if (this.hasError()) {
    name = 'bullet-error';
}
if (this.canZoom() && this.hasError()) {
    name = 'bullet-zoom-error';
}
```

That sounds really ridiculous! You already support multiple css modules, so why do you want force people to concatenate to string?

**Comment by gajus** [comment]
> That sounds really ridiculous! You already support multiple css modules, so why do you want force people to concatenate to string?

Raise the same question with React about `className`.

The problem with your code is that your describing features, not states. Usually, this indication of poor separation of markup and style attributes. But without seeing the actual code, knowing the use case, it is hard to be precise.

**Comment by FredyC** [comment]
No, these are states derived from features. For example when I can zoom onto the bullet, I need to indicate that with different cursor and background color on hover. When there is an error, the bullet gets different color. When something gets selected in the app, the bullet represents that by a different color...and so on. How else could I express that except really putting CSS into JS?

I just don't get it why it's bad to support multiple css modules but avoid using array. I don't know why React has className that way. It sounds rather odd forcing developers to use arbitrary delimiter (space) and breaking a lot of apps when changing that. It couldn't happen with the array.

**Comment by gajus** [comment]
The reason React (nowadays Babel) is not allowing array input is that it does not care about the value of className - it is being passed straight to the DOM object. The reason react-css-modules do not allow array is because it wants to be consistent with className and to encourage use of composition pattern.

**Comment by FredyC** [comment]
You keep talking about this composition, but can you point me to some resource that would help me with my case? I cannot really imagine how I can do it differently.

**Pull request closed without merging**
