### PR TITLE
allow custom styles & fix test case

### PR DESCRIPTION
**Pull request by ustccjw**
1. This PR is make custom styles possible.
    we can pass styles to component to customization style.

2. test/linkClass has some trouble, fixed. (react / react-addons-test-utils upgrade: @0.14.0-rc1)

### CODE REVIEW

**Comment by ustccjw** [comment]
May be we can also add a custom attribute to indicate origin className, then user can base on this attribute to custom ui.

**Comment by ustccjw** [comment]
we can use `css-loader?modules&localIdentName=[local]-[hash:base64:5]` in dev, then we can base `[local]` to set our own styles.

**Comment by ustccjw** [comment]
@gajus

**Comment by ustccjw** [comment]
@gajus sorry, can you check this PR.

**Comment by ustccjw** [comment]
This is usage: https://github.com/ideal-react/ideal-react.github.io/blob/master/src/index.jsx

**Comment by ustccjw** [comment]
@gajus sorry, can you check this PR?

**Comment by forivall** [comment]
@ustccjw you should always @ mention the maintainer when you update a pull request since they don't get automatically notified when you update the PR.

**Comment by gajus** [comment]
I have seen the PR. I do not have time at the moment to review it and come back with a counter solution. In general, the proposed approach feels like a hack. I will think over the weekend how can this be achieved.

**Comment by gajus** [comment]
A variation of this feature has been added. https://github.com/gajus/react-css-modules/tree/3.1.0 Documentation https://github.com/gajus/react-css-modules#extending-component-styles.

**Pull request closed without merging**
