### PR TITLE
fix: Make `styles` property always not enumerable

### LINKED ISSUE #217: `styles` property is not treated as not enumerable if passed to override styles
If I want to override the style of a component doing:

```
<MyComponent styles={overrideStyles} />
```

`MyComponent` will complain that `styles` isn't a valid property, I would expect it to be treated as not enumerable like it happens by default when you don't override the styles.

Sample component:

```
function MyComponent(props) {
  return <div {...props} />;
}
```

Is this intended or a bug?

### PR DESCRIPTION
**Pull request by FezVrasta**
fixes #217

### CODE REVIEW

**Comment by gajus** [comment]
@FezVrasta any reason you've not switched to the `babel-plugin-react-css-modules`?

**Comment by FezVrasta** [comment]
For the moment we prefer to explicitly define the stylings. But we may switch to the babel version in the future.

**Comment by gajus** [comment]
> For the moment we prefer to explicitly define the stylings. But we may switch to the babel version in the future.

Whats inexplicit about `babel-plugin-react-css-modules`?

It will throw errors in every situation where `react-css-modules` does.

(I am not pushing you towards using the other solution. I am just surveying users to understand whats the reason someone would still prefer `react-css-modules` over the Babel version. It might be documentation issue.)

**Comment by FezVrasta** [comment]
We like to have CSSModules explicitly applied to each element because doing so you actually know what's happening, rather than having to check in the Babel settings for some weird plugin that does all this magic under the hood.

Also, with this method you can import an uncompiled component from a different repository and have it working without having to update your Babel config.

This said, we may switch to the Babel version in the future, but for now we are very happy with the current solution.

**Comment by gajus** [comment]
> Also, with this method you can import an uncompiled component from a different repository and have it working without having to update your Babel config.

Thanks. I've made a note of this.

> This said, we may switch to the Babel version in the future, but for now we are very happy with the current solution.

Out of curiosity, have you considered `styled-components`? In terms of performance, `react-css-modules` and `styled-components` are similar (I am not advocating using `styled-components`). If you have, whats the reason you prefer `react-css-modules`?

**Comment by FezVrasta** [comment]
I'm old school and I still think that CSS is a good technology if used responsibly.

Right now we follow a very strict version of BEM where we basically don't make use of the selectors cascade and we simply map classes to elements 1:1.

I think `styled-components` make the management of CSS harder and more difficult to reuse and extend.

But I must admit that I never used them so I may be biased.

**Comment by gajus** [comment]
> I'm old school and I still think that CSS is a good technology if used responsibly.

Same here.

To give some perspective, I've tried `styled-components` on a recent project. Ended up needing completely rewrite the entire (style related) code base at the end of the project to remove `styled-components`. Not only did it have a measurable performance impact, the debugging experience is horrible (rant post is coming; writing a constructive rant takes time).

**Comment by FezVrasta** [comment]
Umh, seems like this thing fixed nothing.
The `styles` prop is set as not enumerable but React throws the error anyway.

Does the babel plugin allow to replace a component style using the `styles` prop? 😅

**Comment by gajus** [comment]
> Does the babel plugin allow to replace a component style using the styles prop? 😅

Of course.

**Comment by FezVrasta** [comment]
I can't find it in the README of the project, may you point it to me pls?

Also, I think this PR fixed the problem only for the class components, I'm trying to fix it for the stateless/functional components as well 🤔

**Comment by gajus** [comment]
> I can't find it in the README of the project, may you point it to me pls?

Just provide it as `styles` property. If I misunderstood you, please provide more details.

**Comment by FezVrasta** [comment]
I just wanted to understand where is this feature documented in the babel plugin project.

**Comment by gajus** [comment]
> I just wanted to understand where is this feature documented in the babel plugin project.

`babel-plugin-...` (the name is seriously too long) is just too fundamental to be documented. `babel...` does not do anything with the `styles` property. Documenting it would be like documenting how to use `setState`.

**Comment by FezVrasta** [comment]
But `styles` isn't a standard property, it's specific to `babele-etcetc` 🤔

**Comment by gajus** [comment]
> But styles isn't a standard property, it's specific to babele-etcetc 🤔

Wait... sorry. I was talking about `style`. `styles` in the context of `babel...` does not exist.

**Comment by FezVrasta** [comment]
Oh, that's a blocker for us 😓 I think I'll keep help maintaining this version..

**Pull request merged**
