### PR TITLE
rendering <noscript> in case of rendering to null

### PR DESCRIPTION
**Pull request by goncalvesjoao**
Hi @gajus first of all, thank you so much for all the work!

I've stumbled upon an error on my app when I started using CSSModules(MyComponent, styles) to render certain Components that given certain conditions would return null, when rendering.

Made some changes to the "src/index.js" file, according to what React 0.11 did for the "Rendering to null" case.
Made some tests too.

I'm currently referencing my fork on my "package.json" so that my app doesn't break, but I'd feel more comfortable referencing your npm package than my fork.
Hit me back if this changes make sense to you or not.
Cheers!

### CODE REVIEW

**Comment by gajus** [comment]
Please resolve the conflicts. Your PR coincided with a recent update.

**Comment by goncalvesjoao** [comment]
sorry. I also kept the original "dist/index.js" I think, that file and the package.json version should be best for you to manage and not me.

**Comment by goncalvesjoao** [comment]
I'm trying to figure out what I did to decrease the overall coverage. sorry, let me check that

**Comment by goncalvesjoao** [comment]
@gajus sorry mate, by creating a spec that didn't existed I've lowered the overall coverage because I'm only testing the changes I made to "src/index.js" and not all of its behaviour.

I could try to make tests for it but I'd probably be missing some of the behaviour that you originally intended for the "functionConstructor" and "decoratorConstructor" functions.

**Comment by gajus** [comment]
@goncalvesjoao please squash together to commits. I will pull it later today and merge it to the mainstream.

**Comment by gajus** [comment]
For reference, this has been closed in favour of https://github.com/gajus/react-css-modules/pull/25.

**Pull request closed without merging**
